# Generated by Django 6.0.2 on 2026-04-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_order_name_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
